### ISSUE TITLE
Script outlines

### ISSUE THREAD

**Issue by carolinetang77** [UBC-MDS/pokemon-type-predictor#12]
Script 1 (downloading data):
input arguments: input file ([here](https://gist.github.com/HansAnonymous/56d3c1f8136f7e0385cc781cf18d486c)), output file name ('data/raw/pokemon.csv')

Script 2 (processing data):
input arguments: file to be read in ('data/raw/pokemon.csv'), folder to write new files to ('data/processed')
replace empty `type2` with `type1`, replace empty `ability2` and `ability hidden` with `ability1`
split data into train (70%) and test (30%), write these to csv files `train.csv`, `test.csv`

Script 3 (EDA):
input arguments: file to be read in ('data/processed/train.csv'), folder to write files to ('results/eda')
creates png files for graphs, csv for tables

Script 4a (kNN):
input arguments: folder containing processed data ('data/processed'), folder to write results to ('results/knn')
column transformations
- one-hot encoding: color, type, abilities
- standard scaling: height, weight, hp, atk, def, sp_atk, sp_def, spd
- passthrough: legendary, mega_evolution
- drop: number, code, serial, name, generation, total
hyperparameter optimization (k)
fit to `train.csv`, score on `test.csv`

Script 4b (SVC):
input arguments: folder containing processed data ('data/processed'), folder to write results to ('results/svc')
column transformations
- one-hot encoding: color, type, abilities
- standard scaling: height, weight, hp, atk, def, sp_atk, sp_def, spd
- passthrough: legendary, mega_evolution
- drop: number, code, serial, name, generation, total
hyperparameter optimization 
fit to `train.csv`, score on `test.csv`

**Comment by WilfHass** [comment]
Combined scripts 4a and 4b as it is redundant code, added some functionality to have one script run either model or all of them!
